### ISSUE TITLE
Doesn't handle special characters

### ISSUE THREAD

**Issue by albertcard** [Komish/mockme#1]
Fix it, please :)

```
# mockme "%hi ^hi &hi $hi #hi @hi !hi *hi"
mockme "%hi ^hi &hi $hi #hi @hi history | grep "\-tt" *hi"
https://goo.gl/g54u4V: %hI ^hI &hI  #Hi @Hi hIsToRy | gReP -tT *hI 
```

**Comment by komish** [comment]
Hi @albertcard 

This is a result of shell expansion of the `!` character (and also probably `*` to some extent). If you wrap your arguments in single quotes like below[1], this should work as expected.

```
mockme '%hi ^hi &hi $hi #hi @hi !hi *hi'
```
